name: Docusaurus-docs-build

# Only trigger on:
# - master branch
# - PR or Pull Request event types
# - Docusaurus files: this file, docs/** 
on:
  push:
    branches:
      - main
      - docusaurus-migration
    paths:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
  pull_request:
    paths:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'

env:
# Used by docusaurus publish-site command and comment-on-pr action
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.event.repository.name }}
  PATCH_SCRIPT_URL: https://raw.githubusercontent.com/DanRoscigno/docs-test/main/config/patch-docusaurus-config.sh
  CONTRIBUTE_SCRIPT_URL: https://raw.githubusercontent.com/finos/open-developer-platform/master/scripts/build-contribute-page.sh

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install docs deps
      run: yarn --cwd docs install
    - name: Patch forked version
      run: |
        # Extract GitHub org/user and patch siteConfig.js only if not "finos"
        REPO="${{ github.repository }}"
        REPO_ORG=${REPO%"/"*}
        if [ "$REPO_ORG" != "finos" ]
        then echo "Repo organization is '$REPO_ORG', patching docusaurus configuration to work on a forked repo" ; curl ${{ env.PATCH_SCRIPT_URL }} |  bash -s -- ${{ env.REPO_NAME }} $REPO_ORG
        else echo "Skipping patching, as this is the FINOS Organization"
        fi
    - name: Build Contributing page
      run: |
        curl ${{ env.CONTRIBUTE_SCRIPT_URL }} |  bash -s
    - name: Install docs deps
      run: yarn --cwd docs build
    - name: Publish docs
      run: |
        # Extract GitHub org/user
        REPO="${{ github.repository }}"
        GIT_USERNAME=${REPO%/*}
        # Set git user to DanRoscigno, if it's a push to a DanRoscigno repo
        if [ "$GIT_USERNAME" == "DanRoscigno" ] && [ "${{github.event_name }}" == "push" ]
        then GIT_USERNAME="DanRoscigno"
        # Configure git client
        echo "Git repo - $REPO"
        echo "Git user - $GIT_USERNAME"
        echo "Event name - ${{github.event_name }}"
        git config --global user.email "$GIT_USERNAME@users.noreply.github.com"
        git config --global user.name "$GIT_USERNAME"
        echo "machine github.com login $GIT_USERNAME password $GITHUB_TOKEN" > ~/.netrc
        # Run docusaurus-publish
        GIT_USER=$GIT_USERNAME yarn --cwd docs publish-gh-pages
# Failing in many situations (ie when a PR comes from a local branch); needs more work and testing before enabling it.
#     - name: Create comment
#       if: github.event_name == 'pull_request'
#       uses: peter-evans/create-or-update-comment@v1
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         issue-number: ${{ github.event.number }}
#         body: Website [preview is available](https://${{ github.actor }}.github.io/${{ env.REPO_NAME }})
